### ISSUE TITLE
Possible Enhancement: Persistent Notification

### ISSUE THREAD

**Issue by coreywilner** [sstratoti/actionable-notifications-subflow-for-ios#10]
Is it possible on iOS to create a persistent notification that cannot be swiped away?  Only way to dismiss is to select an action.

Or, on a swipe away or clear of the notification, get "feedback" into node red that the notification was cleared or swiped away.

**Comment by sstratoti** [comment]
All depends on what events are fired that node-red can listen for.

<img width="625" alt="image" src="https://github.com/sstratoti/actionable-notifications-subflow-for-ios/assets/1392597/f34b0f85-6cc8-423a-bd8f-e37c48ba3008">

In this screenshot we're listening for an ios.notification_action_fired. This allows us to trigger the action associated in the output of the subflow. 

If you spin up an events listener that doesn't have a specified event type with a debug output, you should be able to see what ios events fire (if any)?

**Comment by sstratoti** [comment]
Wanted to update this issue. I can't seem to find a list of iOS events in the documentation. I asked in the HA Discord as well, but didn't receive a response. I think that the next step would be to look at the iOS companion app code itself and try to determine what events are firing from the app that we're able to listen to. 

Unless someone knows how to listen to any events from the bus from a particular domain? I tried ios.* and nothing showed up. And spinning it up with a debug output was...tough to wade through.

Since this issue is not directly related to this subflow and more of a companion app question/issue, I'm going to close it. But please report back if you find anything!
